app/controllers/home_controller.rb, app/controllers/items_controller.rb, app/views/items/index.html.haml, app/views/shared/_footer.html.haml, app/views/shared/_header.html.haml, config/routes.rb
商品出品機能のリンクをトップページに置いた
本番環境で正常に画像が保存されることを確かめるため
=> add-items#new-link

app/assets/stylesheets/modules/header.scss
ヘッダーの色が灰色になっていたため修正
scssのかぶりのため
=> add-header-background-color

README.md, app/assets/stylesheets/adresses.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/users.scss, app/controllers/adresses_controller.rb, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/adresses/new.html.haml, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, config/routes.rb, db/migrate/20200213080649_create_adresses.rb, db/schema.rb
住所登録画面のviewを作成。
新規会員登録後に住所登録画面に遷移するよう変更。
住所登録後はトップ画面へ遷移。
ユーザー情報管理のため。
=> adress_view

app/controllers/items_controller.rb, app/views/items/show.html.haml, config/routes.rb, db/migrate/20200213080649_create_adresses.rb, db/schema.rb
=> 商品削除機能サーバーサイド

db/migrate/20200220055608_add_status_to_user.rb, db/migrate/20200220055742_add_status_to_item.rb, db/migrate/20200220055907_remove_status_from_user.rb, db/schema.rb
=> migrationfile修正

app/controllers/items_controller.rb, app/models/item.rb, db/schema.rb
categoryとのアソシエショーンを解消した。
いったん出品機能を使えるようにする為。
=> 商品出品機能のエラー修正

app/views/adresses/new.html.haml, app/views/devise/registrations/new.html.haml
=> placeholder

app/models/adress.rb, app/views/cards/new.html.haml, db/schema.rb
adressテーブルの任意で登録する箇所にvalidatesがかかってしまっていたので、記述を削除しました。
また、マイページのviewにも一部「＞」のアイコンを表示させていない箇所があったので表示させました。
不備が減ったと思います。
=> address_table_unnecessary 不要な記述の削除

app/assets/stylesheets/modules/footer.scss, app/assets/stylesheets/top.scss, app/views/items/index.html.haml, app/views/shared/_footer.html.haml
一度footer のダウンリードリンクをitems#indeに戻しました
viewが崩れているため
=> bring-footer-to-items#index

README.md
READMEに商品の出品状態を表すカラムを追加しました。
これによりDB設計を完了すると思います。
=> README追加記述

app/assets/javascripts/items.js, app/controllers/adresses_controller.rb
画像を添付→同じボタンを押す→キャンセルする→画像が残ってしまうと言うバグを修正した。
=> 複数画像投稿機能のバグの修正

app/assets/stylesheets/adresses.scss, app/controllers/application_controller.rb, app/views/adresses/new.html.haml, db/migrate/20200224065214_change_data_telephone_number_to_adress.rb, db/schema.rb
userのtelephone_numberのカラムを
integer⇒stringに変更
電話番号のカラムがinteger型であり、
保存ができなかったため。
=> [サーバーサイド]ユーザー住所登録ページのエラー解消

app/assets/stylesheets/users/index.scss, app/views/items/index.html.haml
トップページに画像表示させました。
- 商品のリンクをすべて、商品詳細ページに変更しました。
- 仮置していたものを変更していなかったため。
=> 【マークアップ】modify トップページ

app/views/items/index.html.haml
商品画像がない場合、ニコちゃん画像を表示するようにした
エラーが出ないようにするため
=> 【マークアップ】トップページ　エラーハンドリング

app/views/items/index.html.haml
画像がない場合、editのpathに飛ぶ設定を詳細ページに飛ぶように修正
pathの修正をするため
=> 【マークアップ】トップページ　pathの修正

app/controllers/items_controller.rb, app/views/items/index.html.haml
未購入の商品のみを表示させるようにしました
売り切れの商品は表示させる必要がないため
=> 【サーバーサイド】トップページ　購入済み商品を表示させない

app/models/adress.rb, config/locales/devise.ja.yml
・電話番号は10、11桁でなければ登録できないようにしました。（空欄の場合はそのまま保存される）
・郵便番号は７桁の数字でなければ登録できないようにしました。
=> adressテーブル　バリデーション追加

app/views/items/show.html.haml
詳細画面で複数画像投稿がされていれば、表示されるようにする。
必要な機能だから。
=> 複数画像があれば、表示させるようにする

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/rails_helper.rb
カラムが新たにいくつか追加されたので、テストコードの内容を追加・編集しました。
また、usersコントローラーのテストも追加しました。
バリデーションが正しく行われているか確認する為です。
=> ユーザー新規登録機能　テスト

app/assets/javascripts/cards.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/cards/show.scss, app/views/cards/show.html.haml
・jsを使いhoverされた時にボタンの色が変わるようにした。
・font-sizeの指定
見栄えがよくなる
=> 【マークアップ】カード詳細ページ

app/assets/javascripts/channels/category.js, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/_form.html.haml, app/views/items/new.json.jbuilder, app/views/items/show.html.haml, db/migrate/20200226104707_add_category_id_to_items.rb, db/schema.rb
商品出品ページのカテゴリー機能の実装
カテゴリーカラムの追加
カテゴリーを分けて出品するため。
=> カテゴリー機能　商品出品ページ

app/controllers/purchase_controller.rb, db/migrate/20200227083258_add_buyer_id_to_items.rb, db/schema.rb
buyer_id をitemテーブルに追加した、購入したユーザーが登録されるようにした。
必要な機能だから。
=> 商品購入者のテーブル作成

app/assets/javascripts/users.js, app/controllers/users_controller.rb, app/views/users/_right.html.haml, db/migrate/20200227083258_add_buyer_id_to_items.rb
=> 商品購入と商品出品のマイページ実装

app/assets/javascripts/channels/category.js, app/assets/stylesheets/items_show.scss, app/controllers/items_controller.rb, app/models/category.rb, app/models/item.rb, app/views/items/_form.html.haml, app/views/items/show.html.haml
- 商品 edit の際に、カテゴリーの親、子、孫、全て現れるように修正
- 上記に伴いJSも修正
- 商品 show でカテゴリーが表示されるように修正
- 孫idがDBに保存される仕様であるが、編集の際に親のみで保存が可能であったため。
=> 【バグの修正】商品編集ページ

app/controllers/adresses_controller.rb, app/controllers/application_controller.rb, app/controllers/cards_controller.rb, app/controllers/items_controller.rb, app/controllers/purchase_controller.rb, app/controllers/users_controller.rb, app/views/items/show.html.haml
未ログインユーザーが
ログアウト時→トップページ→商品詳細ページ→購入ボタンを押す→新規会員登録ページ
となるよう修正した
ログインせずに商品の詳細を確認できるようにするため
=> 未ログインユーザーの商品詳細へのアクセスを許可
